all: bloc2 bloc22 bloc224 bloc23 bloc24

bloc2: bloc2.o
	g++ -lGL -lglut bloc2.cpp -o bloc2
bloc22: bloc22.o
	g++ -lGL -lglut bloc22.cpp -o bloc22
bloc224: bloc224.o
	g++ -lGL -lglut bloc224.cpp -o bloc224
bloc23: bloc23.o
	g++ -lGL -lglut bloc23.cpp -o bloc23
bloc24: bloc24.o
	g++ -lGL -lglut bloc24.cpp -o bloc24

clean:
	rm -f *.o bloc2 bloc22 bloc224 bloc23 bloc24 *.cpp~
