all: bloc1 bloc14 bloc15

bloc1: bloc1.o
	g++ -lGL -lglut bloc1.cpp -o bloc1

bloc14: bloc14.o
	g++ -lGL -lglut bloc14.cpp -o bloc14

bloc15: bloc15.o
	g++ -lGL -lglut bloc15.cpp -o bloc15

clean:
	rm -f *.o bloc1 bloc14 bloc15 *.cpp~